# conf/config.yaml

model:
  type: ObjectSpecificSegmentation
  cnnencoder: 
    # You might want to define the encoder architecture here
    # or load it from a separate config file
  num_slots: 2
  num_iterations: 3
  num_classes: 2
  slot_dim: 128
  task: recon
  decoder_type: shared
  learning_rate: 4e-4
  freeze_encoder: true
  temperature: 1
  log_images: false
  lr_warmup: true
  include_seg_loss: false
  softmax_class: false
  slot_attn_type: multi-head
  image_chans: 1
  image_resolution: 128
  embedding_dim: 128

training:
  # Add training-specific parameters here

data:
  # Add data-specific parameters here
  batch_size: 32